FROM node:18.20-alpine

WORKDIR /app/

COPY ./package.json package-lock.json ./

RUN npm ci

# COPY ./src/ /app/
# COPY ./server/ /app/
# COPY ./public/ /app/
# COPY ./messages/ /app/
# COPY *.ts /app/
# COPY *.js /app/

COPY . ./

RUN npm run build

EXPOSE 3000

CMD [ "npm", "run", "dev" ]
