import './globals.css'
import { Inter } from 'next/font/google'

import { NavBar } from '../components/NavBar'
import { Header } from '../components/Header'
import { TopicNav } from '../components/TopicNav'
import { SideBar} from '../components/SideBar'
import { Footer } from '../components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <Header />
        <TopicNav />
        <div className="container mx-auto flex flex-wrap py-6">
          {children}
          <SideBar />
        </div>
        <Footer />
      </body>
    </html>
  )
}
